name: "CD pipeline"

on:
    workflow_run:
        workflows: ["Sample react CI pipeline/workflow"]
        types:
            - completed
jobs:
    deploy:

        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: "Setup Node.js"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Check Node.js Version"
              run: node --version

            - name: "Install Vercel CLI"
              run: npm install -g vercel

            - name: "Download Build Files"
              uses: actions/download-artifact@v4
              with:
                name: product-ready-build
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ github.token }}
            - name: "Deploy to Vercel"
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
              